### ISSUE TITLE
Import: zapracovat a otestovat

### ISSUE THREAD

**Issue by RichardHladik** [trinerdi/icpc-notebook#14]
Zbavit se věcí z /src/import: postupně je přepsat, zdokumentovat, otestovat a přesunout do /src

**Comment by IAmWave** [comment]
Začal bych asi geometrií, ta je dost error-prone a současně asi nejmíň obskurní

**Comment by IAmWave** [comment]
Myslím, že s přidáním KACTL je tenhle issue "vyřešen", protože jsme většinu `import` přestali používat.
