### ISSUE TITLE
Vymyslet způsob jak zjistit, že byl kód opsaný správně

### ISSUE THREAD

**Issue by IAmWave** [trinerdi/icpc-notebook#15]
Můžeme kód nějak hashovat a porovnávat hashe, ale je několik problémů:
- nechceme hashovat whitespace a komentáře
- logika pro testování musí zůstat jednoduchá (nebo jednoduše opsatelná) aby byla použitelná při soutěži

Napadá mě:
- hashovat po řádku a napsat v PDFku ke každému řádku třeba první dva znaky hashe
- nějakým regexem odstranit komentáře a whitespace

**Comment by RiHL288** [comment]
Hashování po řádku (po odstranění whitespace a komentářů) by mohlo fungovat. Kontrola by měla být několik řádků v shellu.

Možné další problémy:
- Někdy chceme opisovaný kód upravovat nebo z něj aspoň části vynechávat. U vynechání celých funkcí by to bylo v pohodě, vynechávání částí funkcí na přeskáčku bude dělat problémy.

IMHO hashování po řádku je pořád nejodolnější (hashování celých funkcí by se rozbilo, protože ↑), ale i tak vyžaduje bystré oko při kontrole hashů.
