### ISSUE TITLE
Sazba: šetřit více místem

### ISSUE THREAD

**Issue by RichardHladik** [trinerdi/icpc-notebook#20]
Nápady:
– vícesloupcová sazba
– vícesloupcová sazba na šířku
– stripování komentářů (#18) a includes
– golfení / jiný coding style: s mírou, lepší, když se nám toho vejde méně, než mít všechno jako obfuskovaný balast

**Comment by IAmWave** [comment]
https://github.com/kth-competitive-programming/kactl/blob/master/kactl.pdf

Tihle to maj naformátovaný hezky

**Comment by RichardHladik** [comment]
Vícesloupcová sazba zavedena s #27, stripování komentářů s #28. V současnosti moc nevidím, jak bychom mohli sazbu ještě více zhustit (a zda je to vůbec potřeba). Zavírám; pokud bude někdy znovu problém s místem, nechť se tato issue znovu otevře.
