### ISSUE TITLE
Seřadit kód v PDF tématicky

### ISSUE THREAD

**Issue by IAmWave** [trinerdi/icpc-notebook#39]
Dělení KACTL vs naše je nepraktické a smíchat zdrojáky je v pohodě, když je autor pořád napsaný v jednotlivých zdrojácích.

**Comment by RichardHladik** [comment]
Určitě, je to přežitek z narychlo provedeného importu a souhlasím, že nemá smysl.

**Comment by IAmWave** [comment]
#49
