### ISSUE TITLE
Dát dohromady teorii čísel

### ISSUE THREAD

**Issue by IAmWave** [trinerdi/icpc-notebook#54]
Různé algoritmy závisí na jiných, takže by to chtělo vybrat je tak, abychom měli i všechny závislosti.

**Comment by RichardHladik** [comment]
Řešeno v #67.
Jediné, co jsme teď bez náhrady odebrali, je počítání modulárního inverzu v okruzích, co nejsou tělesa. Pokud to potřebujeme, jde to buď vytáhnout z `modeq`, nebo použít `fastexp` plus hledání φ(a) pro velká a. Nějakou φ-funkci tam sice máme, ale podle všeho "jen" předpočítává pro všechna a<n. V podstatě to jde převést na faktorizaci, ale to není úplně rychlé. Nápady?

**Comment by RichardHladik** [comment]
Asi není úplně těžké vymyslet inverzy v netělese za běhu; navíc myslím, že to ani nebudeme potřebovat. Zavírám.
